//window object is a global object generated by browser which has js related properties
// window.console.log("helllo");

// dom:all html elements can be accesed in js file in document object
//this document oject is itself present in window object
//  window object-->doc object--->html objects-->head|body
// console.dir(window.document)  used to see object properties and methods
// so basically dom is used to make dynamic changes on our webpage

let heading = document.getElementById("p1");
console.log(heading);
// can also be done through classname and through tags also


//but we will use querySelector...
let k = document.querySelector("#p1");
console.dir(k);

let m = document.querySelectorAll("p");
console.dir(m);

let firstele = document.body.firstChild;    //firstchild : text then comments then element
console.dir(firstele);

let div1 = document.querySelector("#i2");
let div2 = document.querySelector("#i3");
// for updating
div1.innerHTML = "<li>2026</li>";
div2.innerText = "new";


